module.exports = {
  terms: [{ value: 'Spring 2020' }, { value: 'Summer 2020' }, { value: 'Fall 2020' }],
  gurs: [
    { code: 'ACOM', value: 'ACOM - A-Communication GUR' },
    { code: 'ACGM', value: 'ACGM - A-Comparative Gender GUR' },
    { code: 'BCOM', value: 'BCOM - B-Communication GUR' },
    { code: 'BCGM', value: 'BCGM - B-Comparative Gender GUR' },
    { code: 'CCOM', value: 'CCOM - C-Communication GUR' },
    { code: 'HUM', value: 'HUM - Humanities GUR' },
    { code: 'LSCI', value: 'LSCI - Nat Sci with Lab Component GUR' },
    { code: 'SCI', value: 'SCI - Natural Science GUR' },
    { code: 'QSR', value: 'QSR - Quantitative & Symbolic Reasoning GUR' },
    { code: 'SSC', value: 'SSC - Social Sciences GUR' },
  ],
  others: [
    { code: 'AFME', value: 'AFME - HistFieldReq-Africa & Mid East' },
    { code: 'ANCT', value: 'ANCT - HistFieldReq-Ancient' },
    { code: 'ASIA', value: 'ASIA - HistFieldReq-East & South Asia' },
    { code: 'CF', value: 'CF - Communication Focus' },
    { code: 'CF-E', value: 'CF-E - Communication Focus-Economics' },
    { code: 'CMB1', value: 'CMB1 - HistFieldReq-CombReq600-1450CE' },
    { code: 'CMB2', value: 'CMB2 - HistFieldReq-CombReqSince1450' },
    { code: 'CPST', value: 'CPST - Capstone Course' },
    { code: 'EUR', value: 'EUR - HistFieldReq-Europe' },
    { code: 'EUR1', value: 'EUR1 - HistFieldReq-Europe 600-1450CE' },
    { code: 'EUR2', value: 'EUR2 - HistFieldReq-EuropeSince1450CE' },
    { code: 'FIG', value: 'FIG - FIG First Yr Interest Seminar' },
    { code: 'FYE', value: 'FYE - First Year Experience' },
    { code: 'OL', value: 'OL - Online' },
    { code: 'SL', value: 'SL - Service Learning' },
    { code: 'TRVL', value: 'TRVL - Faculty Led Travel' },
    { code: 'US', value: 'US - HistFieldReq-United States' },
    { code: 'US1', value: 'US1 - HistFieldReq-US before 1865' },
    { code: 'US2', value: 'US2 - HistFieldReq-US since 1865' },
    { code: 'WHEM', value: 'WHEM - HistFieldReq-Wstrn Hemisphere' },
    { code: 'WP1', value: 'WP1 - Writing Proficiency 1 point' },
    { code: 'WP2', value: 'WP2 - Writing Proficiency 2 points' },
    { code: 'WP3', value: 'WP3 - Writing Proficiency 3 points' },
  ],
  days: [
    { code: 'U', value: 'Sunday' },
    { code: 'M', value: 'Monday' },
    { code: 'T', value: 'Tuesday' },
    { code: 'W', value: 'Wednesday' },
    { code: 'R', value: 'Thursday' },
    { code: 'F', value: 'Friday' },
    { code: 'S', value: 'Saturday' },
  ],
  subjects: [
    { code: 'A/HI', value: 'A/HI - Art History' },
    { code: 'ACCT', value: 'ACCT - Accounting' },
    { code: 'AECI', value: 'AECI - Arts Enterprise/Cult Innovation' },
    { code: 'AHE', value: 'AHE - Adult and Higher Education' },
    { code: 'AMST', value: 'AMST - American Cultural Studies' },
    { code: 'ANTH', value: 'ANTH - Anthropology' },
    { code: 'ARAB', value: 'ARAB - Arabic' },
    { code: 'ART', value: 'ART - Art' },
    { code: 'ASTR', value: 'ASTR - Astronomy' },
    { code: 'AUAP', value: 'AUAP - Asia University America Program' },
    { code: 'BIOL', value: 'BIOL - Biology' },
    { code: 'BNS', value: 'BNS - Behavioral Neuroscience' },
    { code: 'C/AM', value: 'C/AM - Canadian/American Studies' },
    { code: 'C2C', value: 'C2C - Compass to Campus' },
    { code: 'CD', value: 'CD - Coaching Development' },
    { code: 'CHEM', value: 'CHEM - Chemistry' },
    { code: 'CHIN', value: 'CHIN - Chinese' },
    { code: 'CISS', value: 'CISS - Computer & Info Systems Security' },
    { code: 'CLST', value: 'CLST - Classical Studies' },
    { code: 'COMM', value: 'COMM - Communication Studies' },
    { code: 'CSCI', value: 'CSCI - Computer Science' },
    { code: 'CSD', value: 'CSD - Communication Sci & Disorders' },
    { code: 'CSEC', value: 'CSEC - Collaborative Science & Engineering Collaboration' },
    { code: 'DNC', value: 'DNC - Dance' },
    { code: 'DSCI', value: 'DSCI - Decision Sciences' },
    { code: 'DSGN', value: 'DSGN - Design' },
    { code: 'EAST', value: 'EAST - East Asian Studies' },
    { code: 'ECE', value: 'ECE - Early Childhood Education' },
    { code: 'ECON', value: 'ECON - Economics' },
    { code: 'EDAD', value: 'EDAD - Educational Administration' },
    { code: 'EDUC', value: 'EDUC - Education' },
    { code: 'EE', value: 'EE - Electrical Engineering' },
    { code: 'EGEO', value: 'EGEO - Geography' },
    { code: 'ELED', value: 'ELED - Elementary Education' },
    { code: 'ELL', value: 'ELL - English Language Learners' },
    { code: 'ENG', value: 'ENG - English' },
    { code: 'ENGR', value: 'ENGR - Engineering' },
    { code: 'ENRG', value: 'ENRG - Energy' },
    { code: 'ENTR', value: 'ENTR - Entrepreneurship' },
    { code: 'ENVS', value: 'ENVS - Environmental Studies' },
    { code: 'ESCI', value: 'ESCI - Environmental Sciences' },
    { code: 'ESJ', value: 'ESJ - Education and Social Justice' },
    { code: 'EUS', value: 'EUS - Eurasian Studies' },
    { code: 'FAIR', value: 'FAIR - Fairhaven' },
    { code: 'FIN', value: 'FIN - Finance' },
    { code: 'FREN', value: 'FREN - French' },
    { code: 'GEOL', value: 'GEOL - Geology' },
    { code: 'GERM', value: 'GERM - German' },
    { code: 'GRAD', value: 'GRAD - Graduate Studies' },
    { code: 'GREK', value: 'GREK - Greek' },
    { code: 'HGST', value: 'HGST - Holocaust & Genocide Studies' },
    { code: 'HIST', value: 'HIST - History' },
    { code: 'HLED', value: 'HLED - Health Education' },
    { code: 'HNRS', value: 'HNRS - Honors' },
    { code: 'HRM', value: 'HRM - Human Resource Management' },
    { code: 'HSP', value: 'HSP - Human Services' },
    { code: 'HUMA', value: 'HUMA - Humanities' },
    { code: 'I T', value: 'I T - Instructional Technology' },
    { code: 'IBUS', value: 'IBUS - International Business' },
    { code: 'ID', value: 'ID - Industrial Design' },
    { code: 'IEP', value: 'IEP - Intensive English Program' },
    { code: 'INTL', value: 'INTL - International Studies' },
    { code: 'ITAL', value: 'ITAL - Italian' },
    { code: 'JAPN', value: 'JAPN - Japanese' },
    { code: 'JOUR', value: 'JOUR - Journalism' },
    { code: 'KIN', value: 'KIN - Kinesiology' },
    { code: 'KORE', value: 'KORE - Korean' },
    { code: 'LANG', value: 'LANG - Modern and Classical Language' },
    { code: 'LAT', value: 'LAT - Latin' },
    { code: 'LDST', value: 'LDST - Leadership Studies' },
    { code: 'LIBR', value: 'LIBR - Library' },
    { code: 'LING', value: 'LING - Linguistics' },
    { code: 'M/CS', value: 'M/CS - Mathematics/Computer Science' },
    { code: 'MACS', value: 'MACS - Marine & Coastal Science' },
    { code: 'MATH', value: 'MATH - Mathematics' },
    { code: 'MBA', value: 'MBA - Master of Business Admin' },
    { code: 'MDS', value: 'MDS - Multidisciplinary Studies' },
    { code: 'MFGE', value: 'MFGE - Manufacturing Engineering' },
    { code: 'MGMT', value: 'MGMT - Management' },
    { code: 'MIS', value: 'MIS - Management Information Systems' },
    { code: 'MKTG', value: 'MKTG - Marketing' },
    { code: 'MPAC', value: 'MPAC - Master of Professional ACCT' },
    { code: 'MSCI', value: 'MSCI - Materials Science' },
    { code: 'MUS', value: 'MUS - Music' },
    { code: 'NURS', value: 'NURS - Nursing' },
    { code: 'OPS', value: 'OPS - Operations Management' },
    { code: 'PA', value: 'PA - Physical Activity' },
    { code: 'PCE', value: 'PCE - Plastics&Composite Engineering' },
    { code: 'PE', value: 'PE - Physical Education' },
    { code: 'PHIL', value: 'PHIL - Philosophy' },
    { code: 'PHYS', value: 'PHYS - Physics' },
    { code: 'PLSC', value: 'PLSC - Political Science' },
    { code: 'PORT', value: 'PORT - Portuguese' },
    { code: 'PSY', value: 'PSY - Psychology' },
    { code: 'RC', value: 'RC - Rehabilitation Counseling' },
    { code: 'RECR', value: 'RECR - Recreation' },
    { code: 'REL', value: 'REL - Religion' },
    { code: 'RUSS', value: 'RUSS - Russian' },
    { code: 'SALI', value: 'SALI - Salish Sea Studies' },
    { code: 'SCED', value: 'SCED - Science Education' },
    { code: 'SEC', value: 'SEC - Secondary Education' },
    { code: 'SMNR', value: 'SMNR - Seminar' },
    { code: 'SOC', value: 'SOC - Sociology' },
    { code: 'SPAN', value: 'SPAN - Spanish' },
    { code: 'SPED', value: 'SPED - Special Education' },
    { code: 'TESL', value: 'TESL - Teaching Eng/Second Language' },
    { code: 'THTR', value: 'THTR - Theatre Arts' },
    { code: 'VHCL', value: 'VHCL - Industrial Tech-Vehicle Design' },
    { code: 'WGSS', value: 'WGSS - Women, Gender & Sexuality Study' },
  ],
  sites: [{ code: 'BREX', value: 'WWU Site: Bremerton' }, { code: 'BNEX', value: 'WWU Site: Burien' }, { code: 'DLEX', value: 'WWU Site: Distance Learning' }, { code: 'EVEX', value: 'WWU Site: Everett' }, { code: 'MVEX', value: 'WWU Site: Mt Vernon' }, { code: 'NCEX', value: 'WWU Site: North Cascade Inst' }, { code: 'PAEX', value: 'WWU Site: Port Angeles' }, { code: 'PBEX', value: 'WWU Site: Poulsbo' }, { code: 'NSEX', value: 'WWU Site: Seattle' }, { code: 'TAEX', value: 'WWU Site: Tacoma' }],
};
